name: Docker Build and Push (with Labels & Security)

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Docker Login
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Docker image with labels & metadata
      - name: Build Docker Image
        run: |
          IMAGE_NAME=mano2102/my-html-app
          COMMIT_SHA=${GITHUB_SHA::7}
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          echo "Building Docker Image with metadata..."

          docker build \
            --label org.opencontainers.image.title="My HTML App" \
            --label org.opencontainers.image.description="Simple HTML app with Nginx" \
            --label org.opencontainers.image.authors="Mano <your-email@example.com>" \
            --label org.opencontainers.image.source="https://github.com/${{ github.repository }}" \
            --label org.opencontainers.image.revision=$COMMIT_SHA \
            --label org.opencontainers.image.created=$BUILD_DATE \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$COMMIT_SHA .

      # 4️⃣ Push Docker images
      - name: Push Docker Images
        run: |
          IMAGE_NAME=mano2102/my-html-app
          COMMIT_SHA=${GITHUB_SHA::7}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$COMMIT_SHA

      # 5️⃣ Security scan (Trivy)
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: mano2102/my-html-app:latest
          severity: HIGH,CRITICAL

      # 6️⃣ Verify images locally (optional logs)
      - name: List Docker Images
        run: docker images | grep mano2102/my-html-app
