name: Docker Build Only

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Build the Docker image
      - name: Build Docker Image
        run: docker build -t my-html-app:latest .
