name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t mano2102/my-html-app:latest .

      # 4️⃣ (Optional) Push Docker image
      - name: Push Docker image
        run: docker push mano2102/my-html-app:latest
